steps:
  build-and-push:
    image: woodpeckerci/plugin-kaniko
    settings:
      registry: forgejo.sakul-flee.de
      repo: sakulflee/website
      tags: 
        - ${CI_COMMIT_TAG:-latest}
      dockerfile: Dockerfile
      username:
        from_secret: FORGEJO_USERNAME
      password:
        from_secret: FORGEJO_PASSWORD
    when:
      event: [push, tag, manual]
      branch: main

  create-release:
    image: alpine:latest
    environment:
      FORGEJO_PASSWORD:
        from_secret: FORGEJO_PASSWORD
    commands:
      - apk add --no-cache curl jq
      - |
        curl -X 'POST' "https://forgejo.sakul-flee.de/api/v1/repos/${CI_REPO_OWNER}/${CI_REPO_NAME}/releases" \
             -H "accept: application/json" \
             -H "Authorization: Bearer $FORGEJO_PASSWORD" \
             -H "Content-Type: application/json" \
             -d "{
               \"tag_name\": \"${CI_COMMIT_TAG}\",
               \"target_commitish\": \"${CI_COMMIT_SHA}\",
               \"name\": \"Release ${CI_COMMIT_TAG}\",
               \"body\": \"Automatic release from Woodpecker CI Build #${CI_PIPELINE_NUMBER}\",
               \"draft\": false,
               \"prerelease\": false
             }"
    when:
      event: tag
      branch: main
